name : Generate Ascii

on: push

jobs:
    
    First_job:
        
        runs-on: ubuntu-latest

        steps:
        - name : Step 1
          run :  echo "This is my first job"
        
        - name : Step 2                 
          uses : actions/checkout@v4      # copy repo to the VM
        
        - name : Step 3
          run : ls -ltr     # Print all the file
        
        - name :  Step 4
          run : |        # pipe - used to execute multiple commands in one step
                ls -ltr
                cat README.md
                echo 'all steps ran succesfully'
        
    Second-job :
        needs  : First_job   # accepts string as well of array of strings & need to provide at job level

        runs-on : ubuntu-latest    # files created or modifed in prev job will not reflect those changes in current job as it uses new vm [Sol: use artifacts] 

        steps: 
            - name : job2-step1
              run : sudo apt-get install cowsay -y 

            - name : Execute cowsay Command
              run : cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt
            
            - name : Check File Existency
              run : grep -i "dragon" dragon.txt

            - name : Read File
              run : cat dragon.txt

