name : managing secrets

on : 
  workflow_dispatch:
    inputs:
        action_type:
          description: 'action type'
          required: true
          default: 'create'
          type: choice
          options:
          - create
          - update
          - delete

        gcp_secret_name:
          required: true
          description: 'Secret Name'
          type: string

        gcp_secret_value:
          required: true
          description: 'Secret Value'
          default: 'NA for delete'
          type: string
  
jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - name : Set Secret env
        run : |
          INP_SECRET=$(jq -r '.inputs.gcp_secret_value' $GITHUB_EVENT_PATH)
          echo ::add-mask::$INP_SECRET
          echo SECRET="$INP_SECRET" >> $GITHUB_ENV

      - if : inputs.action_type != 'delete'
        name : Run Command
        run : echo -n $SECRET | gcloud secrets ${{inputs.action_type}} ${{inputs.gcp_secret_name}} --data-file=- --impersonate-service-account=sa-udp-prod-devops-gce-gh@prj-udp-prod-secrets-iiq0jxqkk.iam.gserviceaccount.com --project=prj-udp-prod-secrets-iiq0jxqkk 

      - if : inputs.action_type == 'delete'
        name : Delete Secret
        run : gcloud secrets ${{inputs.action_type}} ${{inputs.gcp_secret_name}}  --impersonate-service-account=sa-udp-prod-devops-gce-gh@prj-udp-prod-secrets-iiq0jxqkk.iam.gserviceaccount.com --project=prj-udp-prod-secrets-iiq0jxqkk
          
        
