name : Manual Dispatch

on : 
  workflow_dispatch:
    inputs:
        logLevel:
          description: 'Log level'
          required: true
          default: 'warning'
          type: choice
          options:
          - create
          - update
          - delete

        tags:
          description: 'Test scenario tags'
          required: false
          type: boolean

        gcp-secret-value:
          description: 'secret string'
          type: string

env:
  LEVEL: ${{ inputs.logLevel }}
  TAGS: ${{ inputs.tags }}
  secret : ${{inputs.gcp-secret-value}}
  
jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "$secret"
        
