name : Matrix Configurations

on : workflow_dispatch

jobs: 
    matrix_jobs:
        strategy:
            matrix:
                os: [ubuntu-latest, ubuntu-20.04, windows-latest]    # all possible combinations runs in parallel 
                images: [hello-world, alphine]

        runs-on : ${{matrix.os}}
        steps :
            - name :  Echo Docker info
              run : docker info
            
            - name : Pull Image in ${{matrix.os}}
              run : docker pull ${{matrix.images}}