name : Multi jobs and artifacts

on : push

jobs :

    Create_artifact:
       
        runs-on : ubuntu-latest

        steps:
            - name : job2-step1
              run : sudo apt-get install cowsay -y 

            - name : Execute cowsay Command
              run : cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt
            
            - name : dragon-text-file-artifact
              uses: actions/upload-artifact@v4
              with:
                name: cowsay-artifact
                path: dragon.txt
    
    Check_artifact:

        needs : Create_artifact

        runs-on: ubuntu-latest

        steps:
            - name : dragon-text-file-artifact-download
              uses: actions/download-artifact@v4
              with:
                name: cowsay-artifact
                
            - name : Check File Existency
              run : grep -i "dragon" dragon.txt

    Run_artifacts:

        needs : Check_artifact

        runs-on : ubuntu-latest
        
        steps:
            - name : dragon-text-file-artifact-download
              uses: actions/download-artifact@v4
              with:
                name: cowsay-artifact

            - name : Read File
              run : cat dragon.txt
